CREATE TABLE products_v6
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account      VARCHAR(255),
    balance      DOUBLE PRECISION,
    product_type VARCHAR(255),
    user_id      VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);